### ISSUE TITLE
version `410.8` causes multiple services to fail on RHCOS

### ISSUE THREAD

**Issue by miabbott** [openshift/redhat-release-coreos#33]
(originally reported downstream https://url.corp.redhat.com/bd1f451)

Moving from `redhat-release-coreos-48-1.el48.x86_64` to `redhat-release-coreos-410.8-1.el8.x86_64` caused a number of services on RHCOS to fail to start.  This can be observed by booting RHCOS `410.8.20190322.0`

When a test build of RHCOS was made using the package set for `410.8.20190322.0`, but using `redhat-release-coreos-48-1.el48.x86_64`, no errors were observed

**Comment by ashcrow** [comment]
Something must have changed other than the version number. Where they both from the same branch?

**Comment by miabbott** [comment]
This turned out to be a bad branch merge in the downstream; closing
